### ISSUE TITLE
2D and 3D input normalization with mean and std.

### ISSUE THREAD

**Issue by huyphan168** [twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows#4]
I noticed in data/data_h36m.py, you normalized the input 2D and 3D with mean and std with specific axes. Can I ask why this effect is too much to the results when I do not use this normalized function? Furthermore, why you would use invert y,z axes by multiplying them with -1?

**Comment by twehrbein** [comment]
Since the network is trained with this type of normalization, it expects all data to be normalized this way.
I believe I inverted the y-axis and z-axis just for visualization purposes. 
You could retrain the model with different type of normalization, it shouldn't make much difference.
