### ISSUE TITLE
Excluding Some Human3.6M CDF Data

### ISSUE THREAD

**Issue by GloryyrolG** [twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows#5]
Hi @twehrbein ,

Found you did really good work! May I ask the reason for excluding some subsets of Human3.6M,

https://github.com/twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows/blob/ad2fdf21da1dfb689a5c2a531ebda6e23d95ccc0/create_data.py#L172

Thanks & regards,

**Comment by twehrbein** [comment]
Hey, thanks for your interest!

To be honest I don't remember why I excluded the sequences. Maybe they somehow got corrupted during preprocessing/downloading. 

Since it's only a really small percentage of the whole dataset, it shouldn't matter performance wise.
