### ISSUE TITLE
BBox Center and Scale Used in 2D HRNet Detection on Human3.6M

### ISSUE THREAD

**Issue by GloryyrolG** [twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows#6]
Hi @twehrbein , @marco-rudolph ,

May I ask a question please? See the title. Are they aligned with the [SPIN](https://github.com/nkolot/SPIN/blob/1e7d8ff4cb0705cf04211760c875098da553c1f8/datasets/preprocess/h36m_train.py#L90) style or [POSENET](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/33e6960fbc81326565a1dd1773e23bcd28f820b4/tool/Human36M/h36m2coco.py#L58) one, or others?

https://github.com/twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows/blob/d09a77387cf0c4ed6862213f94adccdb30bd8a84/data/data_info.txt#L8

Thanks & regards,

**Comment by twehrbein** [comment]
Hey! I computed the bounding box scale and center using the following matlab code snippet, where f indexes the 2d pose:

```
bb = [min(joints(f, : ,1)), min(joints(f, : ,2)), max(joints(f, : ,1)), max(joints(f, : ,2))];
bb_center = round([(bb(1)+bb(3))/2, (bb(2)+bb(4))/2]);
bb_width = bb(3)-bb(1);
bb_height = bb(4)-bb(2);
cropSize = round(max([bb_width, bb_height])*1.2);
crop_bb = round([bb_center(1)-cropSize/2, bb_center(2)-cropSize/2, bb_center(1)+cropSize/2, bb_center(2)+cropSize/2]);
```

Hope that helps.
